"""empty message

Revision ID: 7bc4981c29f5
Revises: f93373b0bd0b
Create Date: 2022-05-31 05:24:17.631519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc4981c29f5'
down_revision = 'f93373b0bd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'favorite')
    # ### end Alembic commands ###
