"""empty message

Revision ID: dacd2e43760d
Revises: dbf786254d1f
Create Date: 2022-05-26 14:30:16.670642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dacd2e43760d'
down_revision = 'dbf786254d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('color', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'color')
    # ### end Alembic commands ###
